version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=plead
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - 3306:3306
    networks:
      - backend
    restart: always
  backend:
    container_name: plead_backend
    depends_on:
      - db
    build:
      context: backend
    image: plead_backend:latest
    ports:
      - 8080:8080
    networks:
      - backend
  front:
    container_name: front
    build:
      context: front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app
    command: ng serve --host=0.0.0.0 --port 4200 --watch --open --poll=2000

networks:
  backend:
