version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - 3306:3306
    restart: always
  backend:
    container_name: plead_backend
    depends_on:
      - db
    build:
      context: backend
    image: plead_backend:latest
    ports:
      - 8080:8080
